name: Build and push to gh-pages branch

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # Gives the workflow access to the repository - https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
            publish_branch: gh-pages
